name: Feature Request
description: Suggest a new feature or enhancement for the application
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving the application. Please provide detailed information about your feature request.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation that this feature would address.
      placeholder: Currently, users are unable to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature in detail.
      placeholder: The application should allow users to...
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: If applicable, describe this feature from a user perspective.
      placeholder: As a [type of user], I want to [perform action] so that [benefit/goal].

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature for your use case?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for functionality
        - Critical - Essential for project requirements
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: What is your estimate of the implementation complexity?
      options:
        - Simple - Minor changes required
        - Moderate - Some development effort needed
        - Complex - Significant development required
        - Unknown - Unable to estimate

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this feature to be considered complete.
      placeholder: |
        - Criterion 1
        - Criterion 2
        - Criterion 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Provide any mockups, diagrams, or additional information that would help clarify this request.
